name: Test Build Action
on: [push]
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew :app:assembleDebug"
